
// 초기 주식 데이터
const initialStocks = [
  // 기술주
  {
    name: "테크 이노베이션",
    price: 55000,
    initialPrice: 55000,
    minListingPrice: 10000,
    isListed: true,
    isManual: false,
    sector: "TECH",
    productType: "stock",
    volatility: 0.05,
    priceHistory: [55000],
  },
  {
    name: "퓨처 모빌리티",
    price: 82000,
    initialPrice: 82000,
    minListingPrice: 15000,
    isListed: true,
    isManual: false,
    sector: "TECH",
    productType: "stock",
    volatility: 0.06,
    priceHistory: [82000],
  },
  // 금융주
  {
    name: "든든 은행",
    price: 42000,
    initialPrice: 42000,
    minListingPrice: 8000,
    isListed: true,
    isManual: false,
    sector: "FINANCE",
    productType: "stock",
    volatility: 0.03,
    priceHistory: [42000],
  },
  {
    name: "글로벌 인베스트",
    price: 71000,
    initialPrice: 71000,
    minListingPrice: 12000,
    isListed: true,
    isManual: false,
    sector: "FINANCE",
    productType: "stock",
    volatility: 0.04,
    priceHistory: [71000],
  },
  // 소비재
  {
    name: "데일리 라이프",
    price: 35000,
    initialPrice: 35000,
    minListingPrice: 7000,
    isListed: true,
    isManual: false,
    sector: "CONSUMER",
    productType: "stock",
    volatility: 0.03,
    priceHistory: [35000],
  },
  // 헬스케어
  {
    name: "바이오 헬스케어",
    price: 95000,
    initialPrice: 95000,
    minListingPrice: 20000,
    isListed: true,
    isManual: false,
    sector: "HEALTHCARE",
    productType: "stock",
    volatility: 0.08,
    priceHistory: [95000],
  },
  // ETF
  {
    name: "ECONOMY TOP 10 ETF",
    price: 100000,
    initialPrice: 100000,
    minListingPrice: 50000,
    isListed: true,
    isManual: false,
    sector: "INDEX",
    productType: "etf",
    volatility: 0.02,
    priceHistory: [100000],
  },
  // 채권
  {
    name: "국고채 5년",
    price: 10000,
    initialPrice: 10000,
    minListingPrice: 9000,
    isListed: true,
    isManual: false,
    sector: "GOVERNMENT",
    productType: "bond",
    volatility: 0.005,
    maturityYears: 5,
    couponRate: 2.5,
    priceHistory: [10000],
  },
];

module.exports = {initialStocks};
