// 학습 사이트 갤러리(알찬 «학습 사이트» 화면)용 썸네일·한 줄 소개 — 앱 id → {image, tagline}.
// 출처: 심티처 포트폴리오(iwsimteacher)의 같은 앱 항목. 새 앱을 등재할 때 여기에도 한 줄 + public/images/learning/<파일>.webp(1200×750)를 추가한다.
// 없는 앱은 갤러리가 아이콘 타일로 그린다(깨지지 않는다).
export const LEARNING_GALLERY = {
  siteArtOn: {"image": "/images/learning/arton.webp", "tagline": "로그인 없이 바로 색칠하는 도안 라이브러리"},
  siteNarae: {"image": "/images/learning/papersky.webp", "tagline": "종이비행기를 날려 보드를 비우는 원터치 퍼즐"},
  siteSeulgisem: {"image": "/images/learning/seulgisem.webp", "tagline": "내 수준에 맞춰 매일 10문제씩"},
  siteNumeroQuest: {"image": "/images/learning/numeroquest.webp", "tagline": "매일 새로운 도전, 매일 더 강해지는 두뇌"},
  siteTypingverse: {"image": "/images/learning/typingverse.webp", "tagline": "손끝으로 여는 무한한 세계"},
  siteEchoTale: {"image": "/images/learning/echotale.webp", "tagline": "AI가 읽어주는 단계별 영어 그림책"},
  siteVocawormDefense: {"image": "/images/learning/vocaworm.webp", "tagline": "단어를 맞히면 포탄이 나가는 학습 디펜스 게임"},
  siteAraharu: {"image": "/images/learning/araharu.webp", "tagline": "매일 아침, 알아가는 즐거움"},
  siteMathCastle: {"image": "/images/learning/mathcastle.webp", "tagline": "문제를 맞혀 마법을 쏘는 수학 타워 디펜스"},
  siteGuguGuardians: {"image": "/images/learning/gugu.webp", "tagline": "계산이 빨라질수록 내 군대가 강해진다"},
  siteChromaFall: {"image": "/images/learning/chromafall.webp", "tagline": "색을 섞어 터뜨리는 낙하 퍼즐"},
  siteKongkongVolley: {"image": "/images/learning/kongkong.webp", "tagline": "3개 키만 알면 되는데, 옆사람과 30분을 싸우게 되는 배구"},
  siteKeywordSchool: {"image": "/images/learning/keywordschool.webp", "tagline": "배움이 곧 열쇠"},
  siteReloadArena: {"image": "/images/learning/reloadarena.webp", "tagline": "물감은 시간으로도 돈으로도 안 나온다 — 문제를 맞혀야 충전된다"},
  sitePickOn: {"image": "/images/learning/iwpick.webp", "tagline": "이름만 넣으면 끝나는 교실 랜덤 추첨"},
  siteNumRush: {"image": "/images/learning/numrush.webp", "tagline": "60초 안에 1부터 순서대로 몇 번까지"},
  siteSpanLand: {"image": "/images/learning/spanland.webp", "tagline": "돌을 세 번 튕겨 집으로 돌아오면 그 안이 내 땅"},
  siteYutDash: {"image": "/images/learning/yutdash.webp", "tagline": "번갈아 윷을 던져 말을 집으로, 남의 말은 잡고"},
  sitePilhan: {"image": "/images/learning/pilhan.webp", "tagline": "눈으로 보는 한자가 아니라, 손으로 쓰는 한자"},
  siteBeatOn: {"image": "/images/learning/beaton.webp", "tagline": "떨어지는 노트를 박자 맞춰 두드리는 리듬 게임"},
  siteSkyGuard: {"image": "/images/learning/skyguard.webp", "tagline": "위에서 쏟아지는 것을, 아래에서 막는다"},
  siteClassVoteBox: {"image": "/images/learning/classvotebox.webp", "tagline": "한 기기를 돌려가며, 비밀은 지켜지는 투표"},
  siteLoopPark: {"image": "/images/learning/looppark.webp", "tagline": "문제를 풀어야 놀이공원이 커진다"},
  siteOreudap: {"image": "/images/learning/oreudap.webp", "tagline": "정답을 밟아야 한 층 오른다"},
  siteKoreaHis: {"image": "/images/learning/koreahis.webp", "tagline": "외우지 말고 근거로 푸는 한국사 문항 5,446개"},
  sitePongdangFishing: {"image": "/images/learning/pongdang.webp", "tagline": "찌를 기다리는 몇 초에, 문제 하나"},
  siteHopSquad: {"image": "/images/learning/hopsquad.webp", "tagline": "문제를 안 풀어도 깰 수 있다 — 맞히면 상만 있다"},
  siteTtobagi: {"image": "/images/learning/ttobagi.webp", "tagline": "급수표를 만들 필요가 없다 — 열면 바로 받아쓰기가 된다"},
  sitePrismPop: {"image": "/images/learning/prism-pop.webp", "tagline": "조각을 맞추다 보면 문제가 끼어든다"},
  siteBatOn: {"image": "/images/learning/baton.webp", "tagline": "타석에 들어서기 전, 문제 하나"},
  sitePinThunder: {"image": "/images/learning/pinthunder.webp", "tagline": "공을 잡고 휘휘 돌려 던지면, 핀 100개가 무너진다"},
  siteTeeshotIsland: {"image": "/images/learning/teeshot.webp", "tagline": "치기 전에 한 문제, 잘 맞히면 더 멀리"},
  siteMichyeonsang: {"image": "/images/learning/michyeonsang.webp", "tagline": "힌트를 사려면 교과 문제를 맞혀야 합니다"},
  siteHwalbaram: {"image": "/images/learning/hwalbaram.webp", "tagline": "바람을 읽고, 흔들림이 멎는 순간에 놓아라"},
  siteSeolbongRush: {"image": "/images/learning/seolbong.webp", "tagline": "한 산을 정상에서 베이스까지, 깃대 사이로 내리꽂는다"},
  siteRacketRush: {"image": "/images/learning/racket-rush.webp", "tagline": "9초짜리 포인트가 쌓여 한 판이 된다 — 쉬는 사이에 문제 하나"},
  siteGoldenWhistle: {"image": "/images/learning/golden-whistle.webp", "tagline": "휘슬이 울리면 작전판을 편다 — 아는 만큼 작전이 통한다"},
  siteGongbunyang: {"image": "/images/learning/gongbunyang.webp", "tagline": "문제를 풀어 모은 별로 내 3D 고양이를 손으로 돌본다 — 공부한 만큼 자란다"},
  siteSchoolStars: {"image": "/images/learning/schoolstars.webp", "tagline": "최대 8명이 실시간으로 붙는 학교 대전 — 판이 끝나면 보너스 퀴즈로 보상이 커진다"},
  siteMulkko: {"image": "/images/learning/mulkko.webp", "tagline": "손가락으로 모래를 파서 물길을 이어 밭에 물을 대면 곡식이 자란다 — 문제는 광고 자리에"},
  siteDosiTambang: {"image": "/images/learning/dosi-tambang.webp", "tagline": "진짜 서울을 하늘에서 보고 내려가 걷는다 — 58곳을 관찰하며 우리 도시를 배운다"},
};

export const galleryInfoFor = (id) => LEARNING_GALLERY[id] || null;
